name: Run Python script on schedule

on:
  schedule:
    - cron: "0 0 * * *"   # รันวันละ 2 ครั้ง (เที่ยงคืน, เที่ยงวัน)
  workflow_dispatch:         # กดรันเองในหน้า Actions ได้ด้วย

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Run script
        run: python main.py
